### ISSUE TITLE
Update team members

### ISSUE THREAD

**Issue by pnijhara** [auvzhcet/auvzhcet_web#24]
Remove past members and add new team members.
@syedjawadakhtar @Khanitachi suggestions?

**Comment by syedjawadakhtar** [comment]
Add all past members in the Alumni page with their passing year.

**Comment by Khanitachi** [comment]
@pnijhara New team members aren't decided yet. We need to update the main page first. Post holders.

**Comment by pnijhara** [comment]
We can update Core members and team heads. And for other teams, we can adjust the present members for now.
This is just to show that our club is not dead. It is actually active.

**Comment by salonigupta1** [comment]
Can i work on this issue?

**Comment by pnijhara** [comment]
The stage is all yours @salonigupta1 
Go ahead!

**Comment by syedjawadakhtar** [comment]
> Add all past members in the Alumni page with their passing year.

To clarify, I wanted to say that you may **shift** the details of team members who have left the club (graduated/yet to be), to the Alumni page. The only thing that has to be added will be their graduation year and branch. 

Removing their details would cause redundant work when adding them to the alumni section.

Regarding inactive or active members, everyone who had been **recruited** would be a club alumnus when he/she leaves. Please make sure that the list of alumni members is in sync with our clubs central directory which was made recently (Contact Management head). As I've no idea who has left the club this year, except 2019-20 pass outs, so the list isn't updated. I hope @pnijhara and @Khanitachi share this info to other members as well so that no one is missed in the list.

Hope this is clear and please do ask when I'm incomprehensible.

**Comment by pnijhara** [comment]
@salonigupta1 progress report?

**Comment by salonigupta1** [comment]
@pnijhara  I will finish this by tomorrow, I didn't have the details of team members, that's why I paused my work. Now I have all the details.
